/****************************************************************************
 * nmeaparser.c
 * openacousticdevices.info
 * July 2020
 *****************************************************************************/

#include <stdlib.h>
#include <string.h>

#include "nmeaparser.h"

/* Structure to maintain state */

typedef struct {
    uint32_t state;
    uint32_t count;
    char buffer[MAX_BUFFER_LENGTH];
    NMEA_parserStatus_t status;
    uint8_t receivedChecksum;
    uint8_t calculatedChecksum;
} NMEA_parserState_t;

/* Macro definitions for updating state */

#define INC_STATE state->state += 1
#define ZERO_STATE state->state = 0
#define SET_STATE(X) state->state = X

#define COUNT state->count
#define INC_COUNT state->count += 1
#define ZERO_COUNT state->count = 0

#define BUFFER state->buffer
#define ADD_TO_BUFFER if (state->count < MAX_BUFFER_LENGTH - 1) {state->buffer[state->count] = c; state->count += 1;}
#define CLEAR_BUFFER memset(state->buffer, 0, MAX_BUFFER_LENGTH); state->count = 0

#define CLEAR_STATE memset(state, 0, sizeof(NMEA_parserState_t))

#define SET_RECEIVED_CHECKSUM(X) state->receivedChecksum = X
#define XOR_RECEIVED_CHECKSUM(X) state->receivedChecksum ^= X

#define SET_CALCULATED_CHECKSUM state->calculatedChecksum = c
#define XOR_CALCULATED_CHECKSUM state->calculatedChecksum ^= c

#define TEST_CHECKSUM_AND_SET_STATUS state->status = state->receivedChecksum == state->calculatedChecksum ? NMEA_SUCCESS : NMEA_CHECKSUM_ERROR

/* Private macro definition for defining jump table functions */

#define _FUNCTION_START(NAME, NUMBER) \
void NAME ## NUMBER (char c, NMEA_parserState_t *state, NMEA_parserResult ## NAME ## _t *result) {if (c == '$') {CLEAR_STATE; state->state = 1; state->status = NMEA_PARSING;} else

#define _FUNCTION_END(STATE, STATUS) \
{state->state = STATE; state->status = STATUS;} }

/* Macro definitions for defining jump table functions */

#define DEFINE_FUNCTION_INIT(NAME, NUMBER) \
_FUNCTION_START(NAME, NUMBER) _FUNCTION_END(0, NMEA_WAITING)

#define DEFINE_FUNCTION_STEP(NAME, NUMBER, CONDITION, ACTION) \
_FUNCTION_START(NAME, NUMBER) if (CONDITION) {ACTION;} else _FUNCTION_END(0, NMEA_CHARACTER_ERROR)

#define DEFINE_FUNCTION_ELSE(NAME, NUMBER, CONDITION1, ACTION1, CONDITION2, ACTION2) \
_FUNCTION_START(NAME, NUMBER) if (CONDITION1) {ACTION1;} else if (CONDITION2) {ACTION2;} else _FUNCTION_END(0, NMEA_CHARACTER_ERROR)

/* Macro definitions handling decimal and hexadecimal digits */

#define CHAR (c)

#define ISCOMMA (c == ',')

#define ISDIGIT ('0' <= c && c <= '9')
#define ISHEXDIGIT (ISDIGIT || ('A' <= c && c <= 'F'))

#define VALUE (c - '0')
#define HEXVALUE (VALUE < 10 ? VALUE : (c - 'A' + 10))

#define ISLETTER ('A' <= c && c <= 'Z')

/* Macro definitions for various character combinations */

#define IS(X) (c == X)

#define ISNUMBER (ISDIGIT || IS('-') || IS('.'))

#define ISVALID (ISLETTER || ISNUMBER || ISCOMMA)

/* Function to copy strings */

void copy(char *dest, const char *src, uint32_t n) {

    uint32_t i = 0;

    while (i < n && src[i] != '\0') {

        dest[i] = src[i];
    
        i += 1;

    }

    while (i < n) {
        
        dest[i] = '\0';

        i += 1;

    }

}

/* Define jump table functions for GGA messages */

DEFINE_FUNCTION_INIT(GGA, 00)
DEFINE_FUNCTION_STEP(GGA, 01, IS('G'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 02, IS('A') || IS('L') || IS('N') || IS('P'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 03, IS('G'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 04, IS('G'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 05, IS('A'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 06, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 07, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->hours = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 08, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->hours += VALUE)
DEFINE_FUNCTION_STEP(GGA, 09, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->minutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 10, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->minutes += VALUE)
DEFINE_FUNCTION_STEP(GGA, 11, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->seconds = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 12, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->seconds += VALUE)
DEFINE_FUNCTION_STEP(GGA, 13, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 14, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds = 100 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 15, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds += 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 16, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds += VALUE)
DEFINE_FUNCTION_STEP(GGA, 17, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(GGA, 18, ISCOMMA, SET_STATE(28); XOR_CALCULATED_CHECKSUM, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDegrees = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 19, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDegrees += VALUE)
DEFINE_FUNCTION_STEP(GGA, 20, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeMinutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 21, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeMinutes += VALUE)
DEFINE_FUNCTION_STEP(GGA, 22, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 23, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths = 1000 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 24, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += 100 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 25, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 26, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += VALUE)
DEFINE_FUNCTION_STEP(GGA, 27, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(GGA, 28, ISCOMMA, SET_STATE(30); XOR_CALCULATED_CHECKSUM, IS('N') || IS('S'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDirection = CHAR)
DEFINE_FUNCTION_STEP(GGA, 29, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(GGA, 30, ISCOMMA, SET_STATE(41); XOR_CALCULATED_CHECKSUM, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees = 100 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 31, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees += 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 32, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees += VALUE)
DEFINE_FUNCTION_STEP(GGA, 33, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeMinutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 34, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeMinutes += VALUE)
DEFINE_FUNCTION_STEP(GGA, 35, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 36, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths = 1000 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 37, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += 100 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 38, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 39, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += VALUE)
DEFINE_FUNCTION_STEP(GGA, 40, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(GGA, 41, ISCOMMA, SET_STATE(43); XOR_CALCULATED_CHECKSUM, IS('E') || IS('W'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDirection = CHAR)
DEFINE_FUNCTION_STEP(GGA, 42, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 43, IS('0') || IS('1') || IS('2'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->positionFixIndicator = CHAR)
DEFINE_FUNCTION_STEP(GGA, 44, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 45, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->satellitesUsed = 10 * VALUE)
DEFINE_FUNCTION_STEP(GGA, 46, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->satellitesUsed += VALUE)
DEFINE_FUNCTION_STEP(GGA, 47, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM; CLEAR_BUFFER)
DEFINE_FUNCTION_ELSE(GGA, 48, ISNUMBER, ADD_TO_BUFFER; XOR_CALCULATED_CHECKSUM, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM; copy(result->horizontalDOP, BUFFER, GGA_BUFFER_LENGTH); CLEAR_BUFFER)
DEFINE_FUNCTION_ELSE(GGA, 49, ISNUMBER, ADD_TO_BUFFER; XOR_CALCULATED_CHECKSUM, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM; copy(result->altitude, BUFFER, GGA_BUFFER_LENGTH))
DEFINE_FUNCTION_STEP(GGA, 50, IS('M'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(GGA, 51, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM; CLEAR_BUFFER)
DEFINE_FUNCTION_ELSE(GGA, 52, ISNUMBER, ADD_TO_BUFFER; XOR_CALCULATED_CHECKSUM, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM; copy(result->geoidalSeparation, BUFFER, GGA_BUFFER_LENGTH))
DEFINE_FUNCTION_STEP(GGA, 53, IS('M'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(GGA, 54, ISVALID, XOR_CALCULATED_CHECKSUM, IS('*'), INC_STATE)
DEFINE_FUNCTION_STEP(GGA, 55, ISHEXDIGIT, INC_STATE; SET_RECEIVED_CHECKSUM(16 * HEXVALUE))
DEFINE_FUNCTION_STEP(GGA, 56, ISHEXDIGIT, ZERO_STATE; XOR_RECEIVED_CHECKSUM(HEXVALUE); TEST_CHECKSUM_AND_SET_STATUS)

void (*const GGAfunctions[])(char, NMEA_parserState_t*, NMEA_parserResultGGA_t*) = {GGA00, GGA01, GGA02, GGA03, GGA04, GGA05, GGA06, GGA07,  \
                                                                                    GGA08, GGA09, GGA10, GGA11, GGA12, GGA13, GGA14, GGA15,  \
                                                                                    GGA16, GGA17, GGA18, GGA19, GGA20, GGA21, GGA22, GGA23,  \
                                                                                    GGA24, GGA25, GGA26, GGA27, GGA28, GGA29, GGA30, GGA31,  \
                                                                                    GGA32, GGA33, GGA34, GGA35, GGA36, GGA37, GGA38, GGA39,  \
                                                                                    GGA40, GGA41, GGA42, GGA43, GGA44, GGA45, GGA46, GGA47,  \
                                                                                    GGA48, GGA49, GGA50, GGA51, GGA52, GGA53, GGA54, GGA55,  \
                                                                                    GGA56};

/* Define jump table functions for RMC messages */

DEFINE_FUNCTION_INIT(RMC, 00)
DEFINE_FUNCTION_STEP(RMC, 01, IS('G'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 02, IS('A') || IS('L') || IS('N') || IS('P'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 03, IS('R'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 04, IS('M'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 05, IS('C'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 06, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 07, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->hours = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 08, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->hours += VALUE)
DEFINE_FUNCTION_STEP(RMC, 09, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->minutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 10, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->minutes += VALUE)
DEFINE_FUNCTION_STEP(RMC, 11, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->seconds = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 12, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->seconds += VALUE)
DEFINE_FUNCTION_STEP(RMC, 13, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 14, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds = 100 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 15, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds += 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 16, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->milliseconds += VALUE)
DEFINE_FUNCTION_STEP(RMC, 17, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 18, IS('A') || IS('V'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->status = CHAR)
DEFINE_FUNCTION_STEP(RMC, 19, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 20, ISCOMMA, SET_STATE(30); XOR_CALCULATED_CHECKSUM, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDegrees = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 21, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDegrees += VALUE)
DEFINE_FUNCTION_STEP(RMC, 22, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeMinutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 23, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeMinutes += VALUE)
DEFINE_FUNCTION_STEP(RMC, 24, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 25, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths = 1000 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 26, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += 100 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 27, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 28, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeTenThousandths += VALUE)
DEFINE_FUNCTION_STEP(RMC, 29, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 30, ISCOMMA, SET_STATE(32); XOR_CALCULATED_CHECKSUM, IS('N') || IS('S'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->latitudeDirection = CHAR)
DEFINE_FUNCTION_STEP(RMC, 31, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 32, ISCOMMA, SET_STATE(43); XOR_CALCULATED_CHECKSUM, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees = 100 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 33, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees += 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 34, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDegrees += VALUE)
DEFINE_FUNCTION_STEP(RMC, 35, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeMinutes = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 36, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeMinutes += VALUE)
DEFINE_FUNCTION_STEP(RMC, 37, IS('.'), INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 38, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths = 1000 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 39, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += 100 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 40, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 41, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeTenThousandths += VALUE)
DEFINE_FUNCTION_STEP(RMC, 42, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 43, ISCOMMA, SET_STATE(45); XOR_CALCULATED_CHECKSUM, IS('E') || IS('W'), INC_STATE; XOR_CALCULATED_CHECKSUM; result->longitudeDirection = CHAR)
DEFINE_FUNCTION_STEP(RMC, 44, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 45, ISNUMBER, XOR_CALCULATED_CHECKSUM, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_ELSE(RMC, 46, ISNUMBER, XOR_CALCULATED_CHECKSUM, ISCOMMA, INC_STATE; XOR_CALCULATED_CHECKSUM)
DEFINE_FUNCTION_STEP(RMC, 47, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->day = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 48, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->day += VALUE)
DEFINE_FUNCTION_STEP(RMC, 49, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->month = 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 50, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->month += VALUE)
DEFINE_FUNCTION_STEP(RMC, 51, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->year = 2000 + 10 * VALUE)
DEFINE_FUNCTION_STEP(RMC, 52, ISDIGIT, INC_STATE; XOR_CALCULATED_CHECKSUM; result->year += VALUE)
DEFINE_FUNCTION_ELSE(RMC, 53, ISVALID, XOR_CALCULATED_CHECKSUM, IS('*'), INC_STATE)
DEFINE_FUNCTION_STEP(RMC, 54, ISHEXDIGIT, INC_STATE; SET_RECEIVED_CHECKSUM(16 * HEXVALUE))
DEFINE_FUNCTION_STEP(RMC, 55, ISHEXDIGIT, ZERO_STATE; XOR_RECEIVED_CHECKSUM(HEXVALUE); TEST_CHECKSUM_AND_SET_STATUS)

void (*const RMCfunctions[])(char, NMEA_parserState_t*, NMEA_parserResultRMC_t*) = {RMC00, RMC01, RMC02, RMC03, RMC04, RMC05, RMC06, RMC07,  \
                                                                                    RMC08, RMC09, RMC10, RMC11, RMC12, RMC13, RMC14, RMC15,  \
                                                                                    RMC16, RMC17, RMC18, RMC19, RMC20, RMC21, RMC22, RMC23,  \
                                                                                    RMC24, RMC25, RMC26, RMC27, RMC28, RMC29, RMC30, RMC31,  \
                                                                                    RMC32, RMC33, RMC34, RMC35, RMC36, RMC37, RMC38, RMC39,  \
                                                                                    RMC40, RMC41, RMC42, RMC43, RMC44, RMC45, RMC46, RMC47,  \
                                                                                    RMC48, RMC49, RMC50, RMC51, RMC52, RMC53, RMC54, RMC55};

/* Define jump table functions for DEFAULT messages */

DEFINE_FUNCTION_INIT(DEFAULT, 00)
DEFINE_FUNCTION_ELSE(DEFAULT, 01, ISVALID, XOR_CALCULATED_CHECKSUM; ADD_TO_BUFFER, IS('*'), INC_STATE; strncpy(result->message, BUFFER, MAX_BUFFER_LENGTH); result->length = COUNT)
DEFINE_FUNCTION_STEP(DEFAULT, 02, ISHEXDIGIT, INC_STATE; SET_RECEIVED_CHECKSUM(16 * HEXVALUE))
DEFINE_FUNCTION_STEP(DEFAULT, 03, ISHEXDIGIT, ZERO_STATE; XOR_RECEIVED_CHECKSUM(HEXVALUE); TEST_CHECKSUM_AND_SET_STATUS)

void (*const DEFAULTfunctions[])(char, NMEA_parserState_t*, NMEA_parserResultDEFAULT_t*) = {DEFAULT00, DEFAULT01, DEFAULT02, DEFAULT03};

/* Define parsers */

static NMEA_parserState_t GGAstate;

NMEA_parserStatus_t NMEAParser_parseGGA(char c, NMEA_parserResultGGA_t *result) {

    GGAfunctions[GGAstate.state](c, &GGAstate, result);

    return GGAstate.status;
 
}

static NMEA_parserState_t RMCstate;

NMEA_parserStatus_t NMEAParser_parseRMC(char c, NMEA_parserResultRMC_t *result) {
    
    RMCfunctions[RMCstate.state](c, &RMCstate, result);

    return RMCstate.status;
    
}

static NMEA_parserState_t DEFAULTstate;

NMEA_parserStatus_t NMEAParser_parseDEFAULT(char c, NMEA_parserResultDEFAULT_t *result) {

    DEFAULTfunctions[DEFAULTstate.state](c, &DEFAULTstate, result);

    return DEFAULTstate.status;

}
